services:
  postgres:
    image: postgres:17-alpine
    container_name: whatsfiled-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: whatsfiled
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d whatsfiled"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
