/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SyncRouteImport } from './routes/sync'
import { Route as SearchRouteImport } from './routes/search'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesSecFilingsRouteImport } from './routes/resources/sec-filings'
import { Route as InsiderCikRouteImport } from './routes/insider.$cik'
import { Route as FilingAccessionNumberRouteImport } from './routes/filing.$accessionNumber'
import { Route as CompanyCikRouteImport } from './routes/company.$cik'

const SyncRoute = SyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSecFilingsRoute = ResourcesSecFilingsRouteImport.update({
  id: '/resources/sec-filings',
  path: '/resources/sec-filings',
  getParentRoute: () => rootRouteImport,
} as any)
const InsiderCikRoute = InsiderCikRouteImport.update({
  id: '/insider/$cik',
  path: '/insider/$cik',
  getParentRoute: () => rootRouteImport,
} as any)
const FilingAccessionNumberRoute = FilingAccessionNumberRouteImport.update({
  id: '/filing/$accessionNumber',
  path: '/filing/$accessionNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyCikRoute = CompanyCikRouteImport.update({
  id: '/company/$cik',
  path: '/company/$cik',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/sync': typeof SyncRoute
  '/company/$cik': typeof CompanyCikRoute
  '/filing/$accessionNumber': typeof FilingAccessionNumberRoute
  '/insider/$cik': typeof InsiderCikRoute
  '/resources/sec-filings': typeof ResourcesSecFilingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/sync': typeof SyncRoute
  '/company/$cik': typeof CompanyCikRoute
  '/filing/$accessionNumber': typeof FilingAccessionNumberRoute
  '/insider/$cik': typeof InsiderCikRoute
  '/resources/sec-filings': typeof ResourcesSecFilingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/sync': typeof SyncRoute
  '/company/$cik': typeof CompanyCikRoute
  '/filing/$accessionNumber': typeof FilingAccessionNumberRoute
  '/insider/$cik': typeof InsiderCikRoute
  '/resources/sec-filings': typeof ResourcesSecFilingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/sync'
    | '/company/$cik'
    | '/filing/$accessionNumber'
    | '/insider/$cik'
    | '/resources/sec-filings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/sync'
    | '/company/$cik'
    | '/filing/$accessionNumber'
    | '/insider/$cik'
    | '/resources/sec-filings'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/sync'
    | '/company/$cik'
    | '/filing/$accessionNumber'
    | '/insider/$cik'
    | '/resources/sec-filings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  SyncRoute: typeof SyncRoute
  CompanyCikRoute: typeof CompanyCikRoute
  FilingAccessionNumberRoute: typeof FilingAccessionNumberRoute
  InsiderCikRoute: typeof InsiderCikRoute
  ResourcesSecFilingsRoute: typeof ResourcesSecFilingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sync': {
      id: '/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/sec-filings': {
      id: '/resources/sec-filings'
      path: '/resources/sec-filings'
      fullPath: '/resources/sec-filings'
      preLoaderRoute: typeof ResourcesSecFilingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insider/$cik': {
      id: '/insider/$cik'
      path: '/insider/$cik'
      fullPath: '/insider/$cik'
      preLoaderRoute: typeof InsiderCikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filing/$accessionNumber': {
      id: '/filing/$accessionNumber'
      path: '/filing/$accessionNumber'
      fullPath: '/filing/$accessionNumber'
      preLoaderRoute: typeof FilingAccessionNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$cik': {
      id: '/company/$cik'
      path: '/company/$cik'
      fullPath: '/company/$cik'
      preLoaderRoute: typeof CompanyCikRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  SyncRoute: SyncRoute,
  CompanyCikRoute: CompanyCikRoute,
  FilingAccessionNumberRoute: FilingAccessionNumberRoute,
  InsiderCikRoute: InsiderCikRoute,
  ResourcesSecFilingsRoute: ResourcesSecFilingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
